// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240306152012_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfAcquisition")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfAcquisition = new DateOnly(2000, 1, 1),
                            DateOfBirth = new DateOnly(1998, 10, 13),
                            EnclosureId = -1,
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 2,
                            DateOfAcquisition = new DateOnly(2001, 2, 3),
                            DateOfBirth = new DateOnly(1997, 9, 18),
                            EnclosureId = -1,
                            Name = "nala",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -1,
                            DateOfAcquisition = new DateOnly(2020, 8, 2),
                            DateOfBirth = new DateOnly(2016, 8, 21),
                            EnclosureId = -1,
                            Name = "lion #-1",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAcquisition = new DateOnly(2020, 12, 13),
                            DateOfBirth = new DateOnly(2019, 1, 6),
                            EnclosureId = -1,
                            Name = "lion #-2",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -3,
                            DateOfAcquisition = new DateOnly(2020, 6, 23),
                            DateOfBirth = new DateOnly(2012, 4, 10),
                            EnclosureId = -1,
                            Name = "lion #-3",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -4,
                            DateOfAcquisition = new DateOnly(2022, 8, 22),
                            DateOfBirth = new DateOnly(2016, 9, 20),
                            EnclosureId = -1,
                            Name = "lion #-4",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -5,
                            DateOfAcquisition = new DateOnly(2022, 1, 8),
                            DateOfBirth = new DateOnly(2016, 1, 7),
                            EnclosureId = -1,
                            Name = "lion #-5",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -6,
                            DateOfAcquisition = new DateOnly(2021, 1, 5),
                            DateOfBirth = new DateOnly(2013, 12, 24),
                            EnclosureId = -1,
                            Name = "lion #-6",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -7,
                            DateOfAcquisition = new DateOnly(2020, 6, 2),
                            DateOfBirth = new DateOnly(2014, 4, 17),
                            EnclosureId = -1,
                            Name = "lion #-7",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -8,
                            DateOfAcquisition = new DateOnly(2021, 10, 20),
                            DateOfBirth = new DateOnly(2017, 8, 27),
                            EnclosureId = -1,
                            Name = "lion #-8",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -9,
                            DateOfAcquisition = new DateOnly(2020, 4, 10),
                            DateOfBirth = new DateOnly(2013, 6, 11),
                            EnclosureId = -6,
                            Name = "lion #-9",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -10,
                            DateOfAcquisition = new DateOnly(2020, 8, 8),
                            DateOfBirth = new DateOnly(2018, 5, 21),
                            EnclosureId = -6,
                            Name = "lion #-10",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -11,
                            DateOfAcquisition = new DateOnly(2020, 7, 2),
                            DateOfBirth = new DateOnly(2018, 1, 28),
                            EnclosureId = -4,
                            Name = "giraffe #-11",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -12,
                            DateOfAcquisition = new DateOnly(2022, 4, 25),
                            DateOfBirth = new DateOnly(2016, 11, 18),
                            EnclosureId = -4,
                            Name = "giraffe #-12",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -13,
                            DateOfAcquisition = new DateOnly(2022, 8, 4),
                            DateOfBirth = new DateOnly(2017, 10, 10),
                            EnclosureId = -4,
                            Name = "giraffe #-13",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -14,
                            DateOfAcquisition = new DateOnly(2021, 3, 22),
                            DateOfBirth = new DateOnly(2016, 9, 6),
                            EnclosureId = -4,
                            Name = "giraffe #-14",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -15,
                            DateOfAcquisition = new DateOnly(2021, 7, 20),
                            DateOfBirth = new DateOnly(2019, 3, 2),
                            EnclosureId = -4,
                            Name = "giraffe #-15",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -16,
                            DateOfAcquisition = new DateOnly(2022, 10, 10),
                            DateOfBirth = new DateOnly(2018, 12, 12),
                            EnclosureId = -4,
                            Name = "giraffe #-16",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -17,
                            DateOfAcquisition = new DateOnly(2021, 4, 23),
                            DateOfBirth = new DateOnly(2012, 6, 6),
                            EnclosureId = -6,
                            Name = "giraffe #-17",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -18,
                            DateOfAcquisition = new DateOnly(2022, 3, 11),
                            DateOfBirth = new DateOnly(2016, 9, 22),
                            EnclosureId = -6,
                            Name = "giraffe #-18",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -19,
                            DateOfAcquisition = new DateOnly(2022, 3, 1),
                            DateOfBirth = new DateOnly(2012, 12, 28),
                            EnclosureId = -6,
                            Name = "giraffe #-19",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -20,
                            DateOfAcquisition = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2016, 10, 14),
                            EnclosureId = -6,
                            Name = "giraffe #-20",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAcquisition = new DateOnly(2022, 7, 27),
                            DateOfBirth = new DateOnly(2019, 5, 12),
                            EnclosureId = -5,
                            Name = "hippo #-21",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -22,
                            DateOfAcquisition = new DateOnly(2022, 10, 5),
                            DateOfBirth = new DateOnly(2015, 7, 16),
                            EnclosureId = -5,
                            Name = "hippo #-22",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -23,
                            DateOfAcquisition = new DateOnly(2021, 8, 10),
                            DateOfBirth = new DateOnly(2016, 1, 27),
                            EnclosureId = -5,
                            Name = "hippo #-23",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -24,
                            DateOfAcquisition = new DateOnly(2022, 5, 26),
                            DateOfBirth = new DateOnly(2013, 2, 22),
                            EnclosureId = -5,
                            Name = "hippo #-24",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -25,
                            DateOfAcquisition = new DateOnly(2021, 8, 8),
                            DateOfBirth = new DateOnly(2018, 6, 15),
                            EnclosureId = -5,
                            Name = "hippo #-25",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -26,
                            DateOfAcquisition = new DateOnly(2020, 6, 3),
                            DateOfBirth = new DateOnly(2016, 6, 1),
                            EnclosureId = -5,
                            Name = "hippo #-26",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -27,
                            DateOfAcquisition = new DateOnly(2021, 6, 23),
                            DateOfBirth = new DateOnly(2018, 12, 12),
                            EnclosureId = -5,
                            Name = "hippo #-27",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -28,
                            DateOfAcquisition = new DateOnly(2022, 10, 12),
                            DateOfBirth = new DateOnly(2013, 12, 1),
                            EnclosureId = -5,
                            Name = "hippo #-28",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -29,
                            DateOfAcquisition = new DateOnly(2020, 9, 13),
                            DateOfBirth = new DateOnly(2018, 4, 21),
                            EnclosureId = -5,
                            Name = "hippo #-29",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -30,
                            DateOfAcquisition = new DateOnly(2022, 4, 27),
                            DateOfBirth = new DateOnly(2010, 5, 16),
                            EnclosureId = -5,
                            Name = "hippo #-30",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAcquisition = new DateOnly(2021, 5, 13),
                            DateOfBirth = new DateOnly(2014, 2, 25),
                            EnclosureId = -2,
                            Name = "eagle #-31",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -32,
                            DateOfAcquisition = new DateOnly(2021, 5, 6),
                            DateOfBirth = new DateOnly(2013, 7, 21),
                            EnclosureId = -2,
                            Name = "eagle #-32",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -33,
                            DateOfAcquisition = new DateOnly(2021, 5, 5),
                            DateOfBirth = new DateOnly(2013, 3, 17),
                            EnclosureId = -2,
                            Name = "eagle #-33",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -34,
                            DateOfAcquisition = new DateOnly(2022, 11, 6),
                            DateOfBirth = new DateOnly(2010, 11, 5),
                            EnclosureId = -2,
                            Name = "eagle #-34",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -35,
                            DateOfAcquisition = new DateOnly(2022, 7, 20),
                            DateOfBirth = new DateOnly(2013, 5, 15),
                            EnclosureId = -2,
                            Name = "eagle #-35",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -36,
                            DateOfAcquisition = new DateOnly(2021, 12, 28),
                            DateOfBirth = new DateOnly(2017, 5, 2),
                            EnclosureId = -2,
                            Name = "eagle #-36",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -37,
                            DateOfAcquisition = new DateOnly(2021, 3, 14),
                            DateOfBirth = new DateOnly(2013, 5, 17),
                            EnclosureId = -2,
                            Name = "eagle #-37",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -38,
                            DateOfAcquisition = new DateOnly(2021, 5, 18),
                            DateOfBirth = new DateOnly(2011, 7, 5),
                            EnclosureId = -2,
                            Name = "eagle #-38",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -39,
                            DateOfAcquisition = new DateOnly(2020, 9, 5),
                            DateOfBirth = new DateOnly(2015, 9, 27),
                            EnclosureId = -2,
                            Name = "eagle #-39",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -40,
                            DateOfAcquisition = new DateOnly(2020, 1, 8),
                            DateOfBirth = new DateOnly(2018, 6, 26),
                            EnclosureId = -2,
                            Name = "eagle #-40",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAcquisition = new DateOnly(2022, 6, 22),
                            DateOfBirth = new DateOnly(2015, 1, 28),
                            EnclosureId = -2,
                            Name = "swan #-41",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -42,
                            DateOfAcquisition = new DateOnly(2020, 12, 7),
                            DateOfBirth = new DateOnly(2012, 4, 3),
                            EnclosureId = -2,
                            Name = "swan #-42",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -43,
                            DateOfAcquisition = new DateOnly(2021, 10, 20),
                            DateOfBirth = new DateOnly(2015, 12, 25),
                            EnclosureId = -2,
                            Name = "swan #-43",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -44,
                            DateOfAcquisition = new DateOnly(2021, 12, 19),
                            DateOfBirth = new DateOnly(2017, 12, 7),
                            EnclosureId = -2,
                            Name = "swan #-44",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -45,
                            DateOfAcquisition = new DateOnly(2020, 1, 26),
                            DateOfBirth = new DateOnly(2019, 7, 3),
                            EnclosureId = -2,
                            Name = "swan #-45",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -46,
                            DateOfAcquisition = new DateOnly(2021, 4, 27),
                            DateOfBirth = new DateOnly(2013, 5, 14),
                            EnclosureId = -2,
                            Name = "swan #-46",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -47,
                            DateOfAcquisition = new DateOnly(2022, 4, 3),
                            DateOfBirth = new DateOnly(2019, 12, 9),
                            EnclosureId = -2,
                            Name = "swan #-47",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -48,
                            DateOfAcquisition = new DateOnly(2020, 11, 10),
                            DateOfBirth = new DateOnly(2017, 2, 17),
                            EnclosureId = -2,
                            Name = "swan #-48",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -49,
                            DateOfAcquisition = new DateOnly(2020, 7, 20),
                            DateOfBirth = new DateOnly(2015, 9, 2),
                            EnclosureId = -2,
                            Name = "swan #-49",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -50,
                            DateOfAcquisition = new DateOnly(2021, 9, 4),
                            DateOfBirth = new DateOnly(2018, 6, 16),
                            EnclosureId = -2,
                            Name = "swan #-50",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAcquisition = new DateOnly(2020, 3, 28),
                            DateOfBirth = new DateOnly(2019, 12, 25),
                            EnclosureId = -3,
                            Name = "python #-51",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -52,
                            DateOfAcquisition = new DateOnly(2022, 12, 11),
                            DateOfBirth = new DateOnly(2017, 8, 11),
                            EnclosureId = -3,
                            Name = "python #-52",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -53,
                            DateOfAcquisition = new DateOnly(2020, 3, 18),
                            DateOfBirth = new DateOnly(2018, 5, 28),
                            EnclosureId = -3,
                            Name = "python #-53",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -54,
                            DateOfAcquisition = new DateOnly(2021, 4, 28),
                            DateOfBirth = new DateOnly(2014, 3, 9),
                            EnclosureId = -3,
                            Name = "python #-54",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -55,
                            DateOfAcquisition = new DateOnly(2020, 3, 25),
                            DateOfBirth = new DateOnly(2010, 11, 9),
                            EnclosureId = -3,
                            Name = "python #-55",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -56,
                            DateOfAcquisition = new DateOnly(2021, 10, 15),
                            DateOfBirth = new DateOnly(2014, 12, 6),
                            EnclosureId = -3,
                            Name = "python #-56",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -57,
                            DateOfAcquisition = new DateOnly(2020, 5, 19),
                            DateOfBirth = new DateOnly(2014, 3, 17),
                            EnclosureId = -3,
                            Name = "python #-57",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -58,
                            DateOfAcquisition = new DateOnly(2020, 10, 13),
                            DateOfBirth = new DateOnly(2016, 10, 13),
                            EnclosureId = -3,
                            Name = "python #-58",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -59,
                            DateOfAcquisition = new DateOnly(2020, 6, 13),
                            DateOfBirth = new DateOnly(2015, 9, 8),
                            EnclosureId = -3,
                            Name = "python #-59",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -60,
                            DateOfAcquisition = new DateOnly(2020, 7, 15),
                            DateOfBirth = new DateOnly(2015, 5, 10),
                            EnclosureId = -3,
                            Name = "python #-60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAcquisition = new DateOnly(2021, 12, 28),
                            DateOfBirth = new DateOnly(2016, 12, 8),
                            EnclosureId = -3,
                            Name = "tortoise #-61",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -62,
                            DateOfAcquisition = new DateOnly(2020, 5, 15),
                            DateOfBirth = new DateOnly(2014, 11, 2),
                            EnclosureId = -3,
                            Name = "tortoise #-62",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -63,
                            DateOfAcquisition = new DateOnly(2021, 1, 21),
                            DateOfBirth = new DateOnly(2010, 1, 16),
                            EnclosureId = -3,
                            Name = "tortoise #-63",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -64,
                            DateOfAcquisition = new DateOnly(2021, 2, 4),
                            DateOfBirth = new DateOnly(2016, 3, 1),
                            EnclosureId = -3,
                            Name = "tortoise #-64",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -65,
                            DateOfAcquisition = new DateOnly(2021, 1, 22),
                            DateOfBirth = new DateOnly(2018, 5, 2),
                            EnclosureId = -3,
                            Name = "tortoise #-65",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -66,
                            DateOfAcquisition = new DateOnly(2020, 9, 9),
                            DateOfBirth = new DateOnly(2013, 10, 13),
                            EnclosureId = -3,
                            Name = "tortoise #-66",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -67,
                            DateOfAcquisition = new DateOnly(2021, 5, 1),
                            DateOfBirth = new DateOnly(2014, 11, 10),
                            EnclosureId = -3,
                            Name = "tortoise #-67",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -68,
                            DateOfAcquisition = new DateOnly(2022, 10, 8),
                            DateOfBirth = new DateOnly(2011, 3, 22),
                            EnclosureId = -3,
                            Name = "tortoise #-68",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -69,
                            DateOfAcquisition = new DateOnly(2021, 3, 16),
                            DateOfBirth = new DateOnly(2019, 9, 7),
                            EnclosureId = -3,
                            Name = "tortoise #-69",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -70,
                            DateOfAcquisition = new DateOnly(2021, 4, 5),
                            DateOfBirth = new DateOnly(2012, 1, 7),
                            EnclosureId = -3,
                            Name = "tortoise #-70",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAcquisition = new DateOnly(2022, 5, 12),
                            DateOfBirth = new DateOnly(2011, 3, 25),
                            EnclosureId = -6,
                            Name = "jellyfish #-71",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -72,
                            DateOfAcquisition = new DateOnly(2020, 11, 28),
                            DateOfBirth = new DateOnly(2019, 12, 23),
                            EnclosureId = -6,
                            Name = "jellyfish #-72",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -73,
                            DateOfAcquisition = new DateOnly(2021, 1, 16),
                            DateOfBirth = new DateOnly(2017, 6, 12),
                            EnclosureId = -6,
                            Name = "jellyfish #-73",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -74,
                            DateOfAcquisition = new DateOnly(2021, 1, 27),
                            DateOfBirth = new DateOnly(2019, 12, 20),
                            EnclosureId = -6,
                            Name = "jellyfish #-74",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -75,
                            DateOfAcquisition = new DateOnly(2022, 7, 20),
                            DateOfBirth = new DateOnly(2019, 7, 8),
                            EnclosureId = -6,
                            Name = "jellyfish #-75",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -76,
                            DateOfAcquisition = new DateOnly(2022, 11, 2),
                            DateOfBirth = new DateOnly(2014, 8, 15),
                            EnclosureId = -6,
                            Name = "jellyfish #-76",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -77,
                            DateOfAcquisition = new DateOnly(2022, 8, 1),
                            DateOfBirth = new DateOnly(2015, 5, 1),
                            EnclosureId = -6,
                            Name = "jellyfish #-77",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -78,
                            DateOfAcquisition = new DateOnly(2022, 10, 21),
                            DateOfBirth = new DateOnly(2011, 12, 16),
                            EnclosureId = -6,
                            Name = "jellyfish #-78",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -79,
                            DateOfAcquisition = new DateOnly(2021, 7, 15),
                            DateOfBirth = new DateOnly(2018, 10, 22),
                            EnclosureId = -6,
                            Name = "jellyfish #-79",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -80,
                            DateOfAcquisition = new DateOnly(2021, 8, 23),
                            DateOfBirth = new DateOnly(2012, 5, 26),
                            EnclosureId = -6,
                            Name = "jellyfish #-80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAcquisition = new DateOnly(2021, 7, 12),
                            DateOfBirth = new DateOnly(2018, 2, 11),
                            EnclosureId = -6,
                            Name = "seahorse #-81",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -82,
                            DateOfAcquisition = new DateOnly(2021, 1, 22),
                            DateOfBirth = new DateOnly(2016, 1, 4),
                            EnclosureId = -6,
                            Name = "seahorse #-82",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -83,
                            DateOfAcquisition = new DateOnly(2021, 1, 27),
                            DateOfBirth = new DateOnly(2012, 3, 8),
                            EnclosureId = -6,
                            Name = "seahorse #-83",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -84,
                            DateOfAcquisition = new DateOnly(2020, 7, 11),
                            DateOfBirth = new DateOnly(2015, 3, 9),
                            EnclosureId = -6,
                            Name = "seahorse #-84",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -85,
                            DateOfAcquisition = new DateOnly(2022, 5, 24),
                            DateOfBirth = new DateOnly(2016, 12, 15),
                            EnclosureId = -6,
                            Name = "seahorse #-85",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -86,
                            DateOfAcquisition = new DateOnly(2020, 11, 3),
                            DateOfBirth = new DateOnly(2019, 5, 17),
                            EnclosureId = -6,
                            Name = "seahorse #-86",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -87,
                            DateOfAcquisition = new DateOnly(2022, 6, 7),
                            DateOfBirth = new DateOnly(2019, 2, 17),
                            EnclosureId = -6,
                            Name = "seahorse #-87",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -88,
                            DateOfAcquisition = new DateOnly(2022, 9, 11),
                            DateOfBirth = new DateOnly(2017, 10, 3),
                            EnclosureId = -6,
                            Name = "seahorse #-88",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -89,
                            DateOfAcquisition = new DateOnly(2020, 5, 24),
                            DateOfBirth = new DateOnly(2014, 3, 11),
                            EnclosureId = -6,
                            Name = "seahorse #-89",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -90,
                            DateOfAcquisition = new DateOnly(2021, 1, 14),
                            DateOfBirth = new DateOnly(2014, 3, 4),
                            EnclosureId = -6,
                            Name = "seahorse #-90",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAcquisition = new DateOnly(2022, 7, 4),
                            DateOfBirth = new DateOnly(2010, 1, 23),
                            EnclosureId = -6,
                            Name = "octopus #-91",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -92,
                            DateOfAcquisition = new DateOnly(2020, 2, 15),
                            DateOfBirth = new DateOnly(2012, 10, 2),
                            EnclosureId = -6,
                            Name = "octopus #-92",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -93,
                            DateOfAcquisition = new DateOnly(2022, 3, 22),
                            DateOfBirth = new DateOnly(2019, 2, 9),
                            EnclosureId = -6,
                            Name = "octopus #-93",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -94,
                            DateOfAcquisition = new DateOnly(2020, 6, 3),
                            DateOfBirth = new DateOnly(2018, 11, 26),
                            EnclosureId = -6,
                            Name = "octopus #-94",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -95,
                            DateOfAcquisition = new DateOnly(2021, 12, 11),
                            DateOfBirth = new DateOnly(2017, 5, 9),
                            EnclosureId = -6,
                            Name = "octopus #-95",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -96,
                            DateOfAcquisition = new DateOnly(2020, 8, 28),
                            DateOfBirth = new DateOnly(2011, 6, 27),
                            EnclosureId = -6,
                            Name = "octopus #-96",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -97,
                            DateOfAcquisition = new DateOnly(2021, 2, 28),
                            DateOfBirth = new DateOnly(2016, 11, 13),
                            EnclosureId = -6,
                            Name = "octopus #-97",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -98,
                            DateOfAcquisition = new DateOnly(2020, 7, 4),
                            DateOfBirth = new DateOnly(2013, 4, 17),
                            EnclosureId = -6,
                            Name = "octopus #-98",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -99,
                            DateOfAcquisition = new DateOnly(2021, 10, 28),
                            DateOfBirth = new DateOnly(2017, 8, 14),
                            EnclosureId = -6,
                            Name = "octopus #-99",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -100,
                            DateOfAcquisition = new DateOnly(2020, 4, 3),
                            DateOfBirth = new DateOnly(2014, 8, 2),
                            EnclosureId = -6,
                            Name = "octopus #-100",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAcquisition = new DateOnly(2020, 6, 14),
                            DateOfBirth = new DateOnly(2010, 3, 2),
                            EnclosureId = -6,
                            Name = "startfish #-101",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -102,
                            DateOfAcquisition = new DateOnly(2022, 5, 28),
                            DateOfBirth = new DateOnly(2014, 12, 17),
                            EnclosureId = -6,
                            Name = "startfish #-102",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -103,
                            DateOfAcquisition = new DateOnly(2021, 7, 9),
                            DateOfBirth = new DateOnly(2018, 1, 22),
                            EnclosureId = -6,
                            Name = "startfish #-103",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -104,
                            DateOfAcquisition = new DateOnly(2022, 9, 17),
                            DateOfBirth = new DateOnly(2016, 7, 1),
                            EnclosureId = -6,
                            Name = "startfish #-104",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -105,
                            DateOfAcquisition = new DateOnly(2020, 6, 23),
                            DateOfBirth = new DateOnly(2016, 3, 9),
                            EnclosureId = -6,
                            Name = "startfish #-105",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -106,
                            DateOfAcquisition = new DateOnly(2022, 4, 17),
                            DateOfBirth = new DateOnly(2012, 8, 10),
                            EnclosureId = -6,
                            Name = "startfish #-106",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -107,
                            DateOfAcquisition = new DateOnly(2020, 6, 21),
                            DateOfBirth = new DateOnly(2010, 7, 14),
                            EnclosureId = -6,
                            Name = "startfish #-107",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -108,
                            DateOfAcquisition = new DateOnly(2021, 3, 1),
                            DateOfBirth = new DateOnly(2011, 3, 2),
                            EnclosureId = -6,
                            Name = "startfish #-108",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -109,
                            DateOfAcquisition = new DateOnly(2022, 1, 6),
                            DateOfBirth = new DateOnly(2011, 8, 19),
                            EnclosureId = -6,
                            Name = "startfish #-109",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -110,
                            DateOfAcquisition = new DateOnly(2021, 9, 18),
                            DateOfBirth = new DateOnly(2018, 9, 26),
                            EnclosureId = -6,
                            Name = "startfish #-110",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAcquisition = new DateOnly(2022, 1, 13),
                            DateOfBirth = new DateOnly(2015, 10, 11),
                            EnclosureId = -6,
                            Name = "ladybug #-111",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -112,
                            DateOfAcquisition = new DateOnly(2021, 8, 19),
                            DateOfBirth = new DateOnly(2013, 11, 14),
                            EnclosureId = -6,
                            Name = "ladybug #-112",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -113,
                            DateOfAcquisition = new DateOnly(2022, 1, 24),
                            DateOfBirth = new DateOnly(2012, 12, 11),
                            EnclosureId = -6,
                            Name = "ladybug #-113",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -114,
                            DateOfAcquisition = new DateOnly(2020, 10, 25),
                            DateOfBirth = new DateOnly(2010, 6, 27),
                            EnclosureId = -6,
                            Name = "ladybug #-114",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -115,
                            DateOfAcquisition = new DateOnly(2022, 1, 25),
                            DateOfBirth = new DateOnly(2017, 10, 1),
                            EnclosureId = -6,
                            Name = "ladybug #-115",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -116,
                            DateOfAcquisition = new DateOnly(2022, 4, 12),
                            DateOfBirth = new DateOnly(2010, 8, 20),
                            EnclosureId = -6,
                            Name = "ladybug #-116",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -117,
                            DateOfAcquisition = new DateOnly(2022, 11, 26),
                            DateOfBirth = new DateOnly(2018, 8, 4),
                            EnclosureId = -6,
                            Name = "ladybug #-117",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -118,
                            DateOfAcquisition = new DateOnly(2020, 8, 27),
                            DateOfBirth = new DateOnly(2017, 6, 3),
                            EnclosureId = -6,
                            Name = "ladybug #-118",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -119,
                            DateOfAcquisition = new DateOnly(2022, 3, 6),
                            DateOfBirth = new DateOnly(2018, 7, 1),
                            EnclosureId = -6,
                            Name = "ladybug #-119",
                            Sex = 0,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -120,
                            DateOfAcquisition = new DateOnly(2022, 5, 25),
                            DateOfBirth = new DateOnly(2016, 6, 5),
                            EnclosureId = -6,
                            Name = "ladybug #-120",
                            Sex = 1,
                            SpeciesId = -12
                        },
                        new
                        {
                            Id = -121,
                            DateOfAcquisition = new DateOnly(2020, 8, 14),
                            DateOfBirth = new DateOnly(2010, 11, 1),
                            EnclosureId = -6,
                            Name = "bumblebee #-121",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -122,
                            DateOfAcquisition = new DateOnly(2021, 10, 3),
                            DateOfBirth = new DateOnly(2010, 7, 1),
                            EnclosureId = -6,
                            Name = "bumblebee #-122",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -123,
                            DateOfAcquisition = new DateOnly(2020, 12, 16),
                            DateOfBirth = new DateOnly(2014, 11, 19),
                            EnclosureId = -6,
                            Name = "bumblebee #-123",
                            Sex = 1,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -124,
                            DateOfAcquisition = new DateOnly(2021, 10, 25),
                            DateOfBirth = new DateOnly(2010, 7, 10),
                            EnclosureId = -6,
                            Name = "bumblebee #-124",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -125,
                            DateOfAcquisition = new DateOnly(2020, 6, 7),
                            DateOfBirth = new DateOnly(2016, 9, 19),
                            EnclosureId = -6,
                            Name = "bumblebee #-125",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -126,
                            DateOfAcquisition = new DateOnly(2020, 3, 19),
                            DateOfBirth = new DateOnly(2016, 3, 11),
                            EnclosureId = -6,
                            Name = "bumblebee #-126",
                            Sex = 1,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -127,
                            DateOfAcquisition = new DateOnly(2021, 5, 2),
                            DateOfBirth = new DateOnly(2014, 4, 11),
                            EnclosureId = -6,
                            Name = "bumblebee #-127",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -128,
                            DateOfAcquisition = new DateOnly(2020, 2, 16),
                            DateOfBirth = new DateOnly(2016, 8, 6),
                            EnclosureId = -6,
                            Name = "bumblebee #-128",
                            Sex = 1,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -129,
                            DateOfAcquisition = new DateOnly(2020, 5, 9),
                            DateOfBirth = new DateOnly(2017, 8, 8),
                            EnclosureId = -6,
                            Name = "bumblebee #-129",
                            Sex = 0,
                            SpeciesId = -13
                        },
                        new
                        {
                            Id = -130,
                            DateOfAcquisition = new DateOnly(2021, 10, 13),
                            DateOfBirth = new DateOnly(2013, 1, 27),
                            EnclosureId = -6,
                            Name = "bumblebee #-130",
                            Sex = 1,
                            SpeciesId = -13
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "lions"
                        },
                        new
                        {
                            Id = -2,
                            Name = "aviary"
                        },
                        new
                        {
                            Id = -3,
                            Name = "reptile"
                        },
                        new
                        {
                            Id = -4,
                            Name = "giraffe"
                        },
                        new
                        {
                            Id = -5,
                            Name = "hippo"
                        },
                        new
                        {
                            Id = -6,
                            Name = "remaining animals"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 0,
                            Name = "giraffe"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 0,
                            Name = "hippo"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 2,
                            Name = "eagle"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 2,
                            Name = "swan"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 1,
                            Name = "python"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 1,
                            Name = "tortoise"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 4,
                            Name = "jellyfish"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 4,
                            Name = "seahorse"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 5,
                            Name = "octopus"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 5,
                            Name = "startfish"
                        },
                        new
                        {
                            Id = -12,
                            Classification = 3,
                            Name = "ladybug"
                        },
                        new
                        {
                            Id = -13,
                            Classification = 3,
                            Name = "bumblebee"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Enclosure", "Enclosure")
                        .WithMany()
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
